sudo: false

language: node_js

cache:
  directories:
    - "node_modules"

node_js:
  - "7"
  - "8"

services:
  - mongodb

before_script:
  - sleep 3

install:
  - npm install -g codecov
  - yarn install

script:
  - yarn test -- --coverage

after_success:
  - codecov
